# Server Port
server.port=8080

# PostgreSQL and PostGIS Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/smartcity
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate Properties
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging levels
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
